### ISSUE TITLE
docker-compose up - timeout of 10000ms exceeded

### ISSUE THREAD

**Issue by jcc2303** [ricca509/dockerize-webdriverio#1]
Hi Riccardo, 

I am new in docker, I got this issue over ubuntu 16.04 and docker  Version:      1.12.5
if you know how to fix it , thanks.

regards

```sh
docker-compose build
...
docker-compose up
Pulling selenium (selenium/standalone-chrome:latest)...
latest: Pulling from selenium/standalone-chrome
af49a5ceb2a5: Pull complete
8f9757b472e7: Pull complete
e931b117db38: Pull complete
47b5e16c0811: Pull complete
9332eaf1a55b: Pull complete
3279bf4baff3: Pull complete
d17cf35dbd7c: Pull complete
72abb7665dcf: Pull complete
073c4756e069: Pull complete
e663639a45c6: Pull complete
f991a6ef5aa7: Pull complete
8709e226c27e: Pull complete
5a99f258d5bf: Pull complete
a3ff036e9da2: Pull complete
78b1123856ba: Pull complete
d6251d3560a2: Pull complete
42a6339934f2: Pull complete
0284722d0235: Pull complete
ff049e7dd2d4: Pull complete
dff0b24dde3e: Pull complete
6c2f133649c4: Pull complete
Digest: sha256:ee0c846afb6f990e334e8d8995b5536a6206a12ee796532196df60c88772f07c
Status: Downloaded newer image for selenium/standalone-chrome:latest
Creating dockerizewebdriverio_selenium_1
Creating dockerizewebdriverio_app_1
Attaching to dockerizewebdriverio_selenium_1, dockerizewebdriverio_app_1
selenium_1  | WARNING: no logs are available with the 'none' log driver
app_1       | npm info it worked if it ends with ok
app_1       | npm info using npm@3.10.9
app_1       | npm info using node@v6.9.2
app_1       | npm info lifecycle dockerize-webdriverio@1.0.0~pretest: dockerize-webdriverio@1.0.0
app_1       | npm info lifecycle dockerize-webdriverio@1.0.0~test: dockerize-webdriverio@1.0.0
app_1       | 
app_1       | > dockerize-webdriverio@1.0.0 test /app
app_1       | > wdio wdio.conf "--host" "selenium"
app_1       | 
app_1       | 
app_1       | F
app_1       | 
app_1       | 0 passing (43.20s)
app_1       | 1 failing
app_1       | 
app_1       | 1) webdriver.io page should have the right title:
app_1       | timeout of 10000ms exceeded. The execution in the test "webdriver.io page should have the right title" took too long. Try to reduce the run time or increase your timeout for test specs (http://webdriver.io/guide/testrunner/timeouts.html).
app_1       | running chrome
app_1       | Error: timeout of 10000ms exceeded. The execution in the test "webdriver.io page should have the right title" took too long. Try to reduce the run time or increase your timeout for test specs (http://webdriver.io/guide/testrunner/timeouts.html).
app_1       |     at Timeout.<anonymous> (/app/node_modules/wdio-mocha-framework/node_modules/mocha/lib/runnable.js:226:19)
app_1       |     at ontimeout (timers.js:365:14)
app_1       |     at tryOnTimeout (timers.js:237:5)
app_1       |     at Timer.listOnTimeout (timers.js:207:5)
app_1       | 
app_1       | 
app_1       | 
app_1       | npm info lifecycle dockerize-webdriverio@1.0.0~test: Failed to exec test script
app_1       | npm ERR! Test failed.  See above for more details.
dockerizewebdriverio_app_1 exited with code 1
^CGracefully stopping... (press Ctrl+C again to force)
Stopping dockerizewebdriverio_selenium_1 ... done


```

**Comment by ricca509** [comment]
Hey @jcc2303,
are you sure it's not a network problem?
I've tried with the same setup and seems to work for me.
Anything that's preventing it from connecting?
